name: Checkov Security 
run-name: Scan Infrastructure as code
on: 
  pull_request


jobs:
  Checkov-Scan:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout Repository
        id: checkout
        uses: actions/checkout@v3

      - name: Execute Scan
        id: scan
        uses: bridgecrewio/checkov-action@master
        with:
          output_format: sarif
          output_file_path: reports/results.sarif 
          download_external_modules: true 
          log_level: WARNING 
          config_file: examples/checkov.yml
          container_user: 1000 # optional: Define what UID and / or what GID to run the container under to prevent permission issues

      - name: Report Checkov Findings
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: reports/results.sarif 
          category: checkov-scans