name: Terraform Documentation
run-name: Update Terraform Documentation
on: pull_request 
jobs:
  terraform-documentation:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        id: checkout
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Render Documentation
        id: docs
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"
          indention: 1
          recursive: false
